version: "3.9"
services:
  redis:
    image: "redis/redis-stack-server"
    environment:
      - requirepass=password123
    ports:
      - "6379:6379"
  api:
    build: api
    ports:
      - "3000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
  web:
    build: web
    ports:
      - "80:80"